#!/bin/bash

#SBATCH --nodes 1
#SBATCH --ntasks-per-node 24
#SBATCH --time 01:00:00
#SBATCH --account ucb-testing

# ml intel/17.4 impi/17.3 hdf5/1.10.1 netcdf/4.4.1.1 pnetcdf/1.8.1
module load {{modules}}

EXEC={{ior_path}}
VERS=IOR-2.10.1
# EXEC=/projects/rcops/holtat/src/IOR/src/C/IOR
IODIR=/scratch/summit/$USER/swh13/test_files_x
mkdir -p /scratch/summit/$USER/swh13/tests
cd /scratch/summit/$USER/swh13/tests

which mpirun

rm -fr $IODIR
mkdir -p $IODIR

let "w=128"
let "s=1024*1024"
let "i=3"

MPIRUN="mpirun -np"

RESULTS="."

let "tid=1"
XFERS="1048576 262144 32768 4096 1024"
XFERS="262144"
for xfer in `echo $XFERS`
do
       let "n=24"
until [ "$n" -gt 24 ]
do

    let "m=$n/4"
  #TESTS="POSIX MPIIO HDF5 NCMPI"
  TESTS="POSIX MPIIO"
  for test in `echo $TESTS`
  do
    runid="p$n.$xfer.${test}"
    date

    V="  "
    BLOCKS="1 10 1 10 1 10"
    for blocks in `echo $BLOCKS`
    do

      let "block=${xfer} * ${blocks}"

    #fileperproc tests
    ${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -w    -z                  ${V} -F -o $IODIR/testwrite.${runid} -Y -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -w    -z                  ${V} -F -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z                  ${V} -F -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z  -C              ${V} -F -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z  -C -Q $m        ${V} -F -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z  -Z -Q $m        ${V} -F -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z  -Z -Q $m -X  13 ${V} -F -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z  -Z -Q $m -X -13 ${V} -F -o $IODIR/testwrite.${runid}    -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1

    ##shared tests
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -w    -z                  ${V}    -o $IODIR/testwrite.${runid} -Y -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -w                        ${V}    -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z                  ${V}    -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1

    ##test mutually exclusive options
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z  -C              ${V}    -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r    -z  -Z              ${V}    -o $IODIR/testwrite.${runid} -k -e -i${i} -m -t ${xfer} -b ${block}  -d 0.1
    #${MPIRUN} $n ${EXEC} -A ${tid} -a ${test} -r -Z -C                  ${V}    -o $IODIR/testwrite.${runid}       -i${i} -m -t ${xfer} -b ${block}  -d 0.0
    let "tid=$tid + 17"

    V=$V" -v"

    done #blocks

    date
  done #test
  let "n = $n * 2"
 done #n
done #xfer
exit
