#!/bin/bash
#SBATCH --job-name={{job_name}}
#SBATCH --nodes=1
#SBATCH --nodelist={{node_name}}
#SBATCH --time=0:45:00


STREAM=/curc/tools/x86_64/rh6/software/stream/5.10/intel/15.0.2/stream_c.exe
LINPACK=/curc/tools/x86_64/rh6/software/intel/15.0.2/mkl/benchmarks/linpack/xlinpack_xeon64

LINPACK_INPUT="\
Sample Intel(R) Optimized LINPACK Benchmark data file (lininput_xeon64)
Intel(R) Optimized LINPACK Benchmark data
6                     # number of tests
1000 2000 5000 10000 20000 25000# problem sizes
1000 2000 5000 10000 20000 25000 # leading dimensions
2 2 2 1 1 1  # times to run a test
4 4 4 4 4 4  # alignment values (in KBytes)"


function main
{
    module load intel

    $STREAM >stream.out

    echo >linpack_input "${LINPACK_INPUT}"
    $LINPACK linpack_input >linpack.out
}


main
