#!/bin/bash
#SBATCH -N 1
#SBATCH --nodelist={{node_name}}
#SBATCH --time=0:45:00
#SBATCH --reservation={{reservation_name}}
#SBATCH --account=crcbenchmark
#SBATCH --qos=admin

mkdir -p {{node_name}}

# copy linpack
cd {{node_name}}

cat >> linpack_input << EOF
Sample Intel(R) Optimized LINPACK Benchmark data file (lininput_xeon64)
Intel(R) Optimized LINPACK Benchmark data
6                     # number of tests
1000 2000 5000 10000 20000 25000# problem sizes
1000 2000 5000 10000 20000 25000 # leading dimensions
2 2 2 1 1 1  # times to run a test
4 4 4 4 4 4  # alignment values (in KBytes)
EOF

module load openmpi/openmpi-1.6.4_intel-13.0.0_torque-4.1.4_ib

echo "STREAM Memory Bandwidth Test:" > data
#----------------------------------------------------------------------------
export OMP_NUM_THREADS=12
NUM_TRIALS=2
COPYTOTAL=0
SCALETOTAL=0
ADDTOTAL=0
TRIADTOTAL=0
start_time=$(date +%s)
for ((i=0; i < NUM_TRIALS ; i++ ))
do
# Grab the 3 lines in addition to the line starting with Copy
VAR=`./lib/stream/stream-5.9/stream | grep -A 3 Copy`

COPY=`echo $VAR | awk '{ print $2 }' | awk -F. '{ print $1 }'`
COPYTOTAL=$(($COPY + $COPYTOTAL))

SCALE=`echo $VAR | awk '{ print $7 }' | awk -F. '{ print $1 }'`
SCALETOTAL=$(($SCALE + $SCALETOTAL))

ADD=`echo $VAR | awk '{ print $12 }' | awk -F. '{ print $1 }'`
ADDTOTAL=$(($ADD + $ADDTOTAL))

TRIAD=`echo $VAR | awk '{ print $17 }' | awk -F. '{ print $1 }'`
TRIADTOTAL=$(($TRIAD + $TRIADTOTAL))

done
end_time=$(date +%s)
echo $((end_time - start_time)) > time_data

echo $((COPYTOTAL/NUM_TRIALS)) " " $((SCALETOTAL/NUM_TRIALS)) " " $((ADDTOTAL/NUM_TRIALS)) " " $((TRIADTOTAL/NUM_TRIALS)) >> data

# Linpack
echo "Linpack CPU Test:" >> data
#----------------------------------------------------------------------------
start_time=$(date +%s)
./lib/linpack/linpack_11.2.2/benchmarks/linpack/xlinpack_xeon64 linpack_input | grep -A 9 Performance >> data
end_time=$(date +%s)
echo $((end_time - start_time)) >> time_data
