#!/bin/bash
#PBS -N job.<JOB_NAME>
#PBS -q janus-jumbo
#PBS -l walltime=<TIME>
#PBS -l nodes=<NODES>:ppn=12
#PBS -j oe

cd $PBS_O_WORKDIR

mkdir -p <JOB_NAME>
cd <JOB_NAME>

cat >> HPL.dat << EOF
HPLinpack benchmark input file
Innovative Computing Laboratory, University of Tennessee
data		 output file name (if any) 
6            device out (6=stdout,7=stderr,file)
1            # of problems sizes (N)
<N>          Ns
1            # of NBs
128           NBs
0            PMAP process mapping (0=Row-,1=Column-major)
1            # of process grids (P x Q)
<P>          Ps
<Q>          Qs
16.0         threshold
1            # of panel fact
2            PFACTs (0=left, 1=Crout, 2=Right)
1            # of recursive stopping criterium
4            NBMINs (>= 1)
1            # of panels in recursion
2            NDIVs
1            # of recursive panel fact.
1            RFACTs (0=left, 1=Crout, 2=Right)
1            # of broadcast
1            BCASTs (0=1rg,1=1rM,2=2rg,3=2rM,4=Lng,5=LnM)
1            # of lookahead depth
1            DEPTHs (>=0)
2            SWAP (0=bin-exch,1=long,2=mix)
64           swapping threshold
0            L1 in (0=transposed,1=no-transposed) form
0            U  in (0=transposed,1=no-transposed) form
1            Equilibration (0=no,1=yes)
8            memory alignment in double (> 0)
EOF

. /curc/tools/utils/dkinit
use .openmpi-1.4.5_intel-12.1.2

mpirun -np <PROCESSORS> /curc/admin/benchmarks/bin/xhpl > data

